# Generated by Django 5.1.4 on 2025-02-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_signupdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(blank=True, max_length=50, null=True)),
                ('ProductName', models.CharField(blank=True, max_length=50, null=True)),
                ('Quantity', models.IntegerField(blank=True, max_length=50, null=True)),
                ('Price', models.IntegerField(blank=True, max_length=50, null=True)),
                ('TotalPrice', models.IntegerField(blank=True, max_length=50, null=True)),
                ('Product_Image', models.ImageField(blank=True, max_length=50, null=True, upload_to='')),
            ],
        ),
    ]
