# Generated by Django 5.1.4 on 2025-02-04 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_cartdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdb',
            old_name='ProductName',
            new_name='Product_Name',
        ),
    ]
