# Generated by Django 5.1.4 on 2025-02-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_checkoutdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdb',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartdb',
            name='Quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartdb',
            name='TotalPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
