# Generated by Django 5.1.4 on 2025-02-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_alter_cartdb_price_alter_cartdb_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdb',
            name='TotalPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
